[Task] Exercise structure layout html page home1
cmvn-truongle/FE-Internship-2023_Truong-Le-D_FE-Exercise pull request #5
Opened 2023-08-04 08:40 UTC by cmvn-truongle

### Description
- structure layout html page home1

### Checklist
- [x] App run correctly
- [x] The code has been tested in the local environment.
- [x] No convention errors

2023-08-05 17:46 UTC, st-duynguyen commented on README.md
> +### References
Checkout những file ko liên quan tới bài tập trong PR

2023-08-05 17:46 UTC, st-duynguyen commented on index.html
> +  <title>Document</title>
Đặt title cho chuẩn mục đích của web, vì nó sẽ ảnh hưởng tới SEO

2023-08-05 17:48 UTC, st-duynguyen commented on index.html
> +        <img src="" alt="">
Tạo thư mục assets/images rồi download tất cả những image bỏ vào để dùng

2023-08-05 17:49 UTC, st-duynguyen commented on index.html
> +        <h3>E-shop</h3>
Bỏ thẻ h1 bọc cho cả header logo (bao gồm image vs title E-shop)

2023-08-05 17:52 UTC, st-duynguyen commented on index.html
> +        <ul>
Trong yêu cầu bài tập có yêu cầu đặt tên class cho các thẻ, nên e check lại 1 lượt, đặt tên lại cho những thẻ có trong bài

2023-08-05 17:53 UTC, st-duynguyen commented on index.html
> +          <li><i></i></li>
Làm lại chi tiết bài tập, yêu cầu phải có image, alt, class, làm như vậy quá sơ sài

2023-08-05 17:56 UTC, st-duynguyen commented on index.html
> +      <section class="shop">
đặt lại tên class theo format section-nội dung section. Ex: section-top-banner, section-collection. Check lại 1 lượt các thẻ section còn lại

2023-08-05 17:56 UTC, st-duynguyen commented on index.html
> +        <h1>Sale of the summer collection</h1>
Mỗi 1 trang thì chỉ có 1 thẻ h1, và ưu tiên là dùng cho logo.

2023-08-05 18:00 UTC, st-duynguyen commented on index.html
> +          <a href="">Shop now</a>
thẻ a phải vừa bọc cả icon và text

2023-08-05 18:04 UTC, st-duynguyen commented on index.html
> +        <ul class="shop-list">
- e nên đặt class của ul và li liên quan tới nhau 
- ul phải bao quát mục đích của li bên trong
- mục đích ul li và những item hắn list ra giống nhau, nên là nên đặt class li giống nhau
Ex: 
```
<ul class="list-services">
    <li class="list-item"></li>
    <li class="list-item"></li>
</ul>

2023-08-05 18:06 UTC, st-duynguyen commented on index.html
> +              <h4>Satisfied-customers</h4>
check lại 1 lượt đặt tên class cho tất cả những thẻ, kể cả thẻ h,p

2023-08-05 18:09 UTC, st-duynguyen commented on index.html
> +            <img src="" alt="">
Trong li chia ra 1 cái div bự chứa 2 phần: image(card-image) và 1 div content (card-detail) chứa title vs price

2023-08-05 18:09 UTC, st-duynguyen commented on index.html
> +          <li class="card">
Check lại comment ở trên của a, chia lại div

2023-08-05 18:10 UTC, st-duynguyen commented on index.html
> +          <li class="card">
Tương tự cho thằng này lun

2023-08-05 18:10 UTC, st-duynguyen commented on index.html
> +          <input type="text">
Bọc thẻ form cho 2 thằng input vs button, đặt class hoàn chỉnh

2023-08-05 18:11 UTC, st-duynguyen commented on index.html
> +      <nav class="footer-content">
k nên đặt thẻ nav ở đây

2023-08-05 18:11 UTC, st-duynguyen commented on index.js
> +var a = 3, b = 3;
Checkout những thằng k liên quan ra khỏi file change

2023-08-05 18:12 UTC, st-duynguyen requested changes
@cmvn-truongle 
- Bài làm còn sơ sài. Em phải tải image về, viết html hoàn chỉnh chứ k phải khai báo các thẻ như đang làm, đặt class hoàn chỉnh cho tất cả các thẻ có trong bài.
- Còn tạo thiếu các label đang review

2023-08-06 13:15 UTC, st-duynguyen commented on index.html
> +  <title>Home1</title>
Đổi title lại thành `E-shop`

2023-08-06 13:22 UTC, st-duynguyen commented on index.html
> +        <img src="./assets/images/noun_cloth_2129414.png" alt="img-logo" class="header-logo-img">
bọc bên ngoài img vs title 1 thẻ a vì thường click vào Logo sẽ đi về home

2023-08-06 13:23 UTC, st-duynguyen commented on index.html
> +      <nav class="header-icons">
ở trên đã có thẻ nav dùng cho menu rồi thì thằng này chỉ nên làm thẻ div bọc ul li bình thường

2023-08-06 13:27 UTC, st-duynguyen commented on index.html
> +            <img src="./assets/images/Fashion - home-image5 1.png" alt="home-image-5" class="slides-img">
đặt alt ghi rõ title của image, check lại 1 lượt cho tất cả các thẻ img

2023-08-06 13:38 UTC, st-duynguyen commented on index.html
> +                <p class="benefit-card-name">Free Shipping</p>
Check lại 1 lượt, những title lớn thì nên đặt thẻ h cho nó, k lên đặt thẻ p

2023-08-06 13:41 UTC, st-duynguyen commented on index.html
> +  <div class="home-container">
div container nên là 1 div con bọc ở trong những section bự chứ k bọc ngoài như này

2023-08-06 13:44 UTC, st-duynguyen commented on index.html
> +        <ul class="list-icons">
đặt class cho clear từng chức năng của ul. Ex trong trường hợp này có thể là: social-network-list

2023-08-06 13:45 UTC, st-duynguyen commented on index.html
> +            most importantly, for
E check lại 1 lượt tất cả những text dài của e, sao a thấy nó bị xún nhiều hàng vậy

2023-08-06 13:46 UTC, st-duynguyen commented on index.html
> +      <div class="footer-content-list">
Chỗ này mỗi cục div sẽ khác nhau, k phải là ul li nên là e ko nên đặt tên chung là `footer-content-list` giống nhau hết như vậy

2023-08-07 10:08 UTC, st-duynguyen commented on index.html
> +          <li class="menu-item">
Thằng li của ul này cơ bản hắn khác vs những li của ul trên nên e k nên đặt chung tên là `menu-item`

2023-08-07 10:10 UTC, st-duynguyen commented on index.html
> +            <a class="text-uppercase categoris-content-link">more details</a>
Chỗ này nên dùng button chứ k phải là thẻ a, e check lại 1 lượt tất cả những chỗ nên dùng thẻ a hay là button

2023-08-07 10:10 UTC, st-duynguyen commented on index.html
> +            <a class="text-uppercase categoris-content-link">more details</a>
sửa thành button thì nên sửa lại mấy class bên trong lun

2023-08-07 10:11 UTC, st-duynguyen commented on index.html
> +        <h3 class="product-title-name">Selected just for you</h3>
Nếu thằng trên đã là h3 thì thằng này phải là h2, check cho những title bự ở ngoài ul li thì để h2

2023-08-07 10:32 UTC, cmvn-truongle commented on index.html
> +            <a class="text-uppercase categoris-content-link">more details</a>
dạ là giờ để thẻ a hay đổi thành button anh

2023-08-07 15:19 UTC, st-duynguyen commented on index.html
> +              <h6 class="product-card-desc">T-Shirt Summer Vibes</h6>
Check lại lun cả mấy thằng dưới, a nói là những title ở trong card là để h4 hết mà e

2023-08-07 15:20 UTC, st-duynguyen commented on index.html
> +              <h6 class="today-product-card-name">T-Shirt Summer Vibes</h6>
Đây nữa, những title trong content là để h4 hết

2023-08-07 15:20 UTC, st-duynguyen commented on index.html
> +        <li class="social-network-item"><i class="social-network-icon"></i></li>
Check lại 1 lượt hết các li của footer nha e, thiếu thẻ a bọc ngoài icon rồi

2023-08-07 16:11 UTC, st-duynguyen approved these changes
LGTM

2023-08-07 23:32 UTC, merged