css for E-shop page
cmvn-truongle/FE-Internship-2023_Truong-Le-D_FE-Exercise pull request #7
Opened 2023-08-08 10:07 UTC by cmvn-truongle

### Description
- css for E-shop page

### Checklist
- [x] App run correctly
- [x] The code has been tested in the local environment.
- [x] No convention errors

2023-08-08 16:45 UTC, st-trangnguyen requested changes
Bài này em sai nhiều, em fix theo feedback dưới đây để hệ thống layout lại đã rồi fix tiếp.
- define variable cho color
- define container
- xây dựng grid layout (row-column)
- em xây dựng css cho các module button, badge (cái tag giảm bao nhiều % giá), section header để có tính tái sử dụng cao
ví dụ: btn btn-primary, btn btn-secondary, btn btn-outline, badge badge-danger, section-header.section-header-center (cái nào có button show more thì section-header còn cái nào title cần vào giữa thì thêm class section-header-center zo)
tham khảo thêm bootstrap về cách xây dựng các utility, module...
https://getbootstrap.com/docs/4.0/layout/overview/#containers
https://getbootstrap.com/docs/4.0/layout/grid/
https://getbootstrap.com/docs/4.0/layout/media-object/
https://getbootstrap.com/docs/4.0/utilities/flex/
https://getbootstrap.com/docs/4.0/utilities/text/
https://getbootstrap.com/docs/4.0/components/card/
https://getbootstrap.com/docs/4.0/components/buttons/
https://getbootstrap.com/docs/4.0/components/badge/
https://getbootstrap.com/docs/4.0/components/forms/
https://getbootstrap.com/docs/4.0/components/navs/

2023-08-09 14:23 UTC, st-ngabui commented on style/button.css
> +}
Thêm end line vào e, check lỗi tương tự ở file khác

2023-08-09 14:23 UTC, st-ngabui commented on style/button.css
> +    cursor: pointer;
Nên khai báo thêm padding, border-radius cho btn nữa e

2023-08-09 14:23 UTC, st-ngabui commented on index.html
> +  <link rel="stylesheet" href="./style/responsive.css">
Em nên để ý thứ tự import CSS vì những CSS được import sau có thể ghi đè lên cái trước

2023-08-09 14:23 UTC, st-ngabui commented on style/flex.css
> +}
Tại sao e lại sử dụng CSS này

2023-08-09 14:23 UTC, st-ngabui commented on index.html
> +        </h1>
Em đang bị duplicate code cho phần header

2023-08-09 14:43 UTC, st-ngabui requested changes

2023-08-09 14:43 UTC, st-ngabui commented on style/font.css
> +}
E khai báo màu sắc cho text thì nên đặt class là txt-{name-color}

2023-08-09 14:43 UTC, st-ngabui commented on style/style.css
> +}
Em xây dựng CSS cho module badge và sử dụng lại ở các chỗ khác nữa

2023-08-09 14:43 UTC, st-ngabui commented on style/style.css
> +    padding: 96px 0 60px 0;
Chị thấy thông số này đang sai với design, check lại em nghe

2023-08-09 14:43 UTC, st-ngabui commented on style/flex.css
> +}
Chị thấy dòng này không có cần thiết khi e đã khai báo class cho col rồi

2023-08-10 02:38 UTC, merged