[Task] convert code css to scss for e-shop web
cmvn-truongle/FE-Internship-2023_Truong-Le-D_FE-Exercise pull request #9
Opened 2023-08-10 10:08 UTC by cmvn-truongle

### Description
- Convert code css to scss for e-shop web
- 
[screencapture-127-0-0-1-5500-index-html-2023-08-10-17_06_43.pdf](https://github.com/cmvn-truongle/FE-Internship-2023_Truong-Le-D_FE-Exercise/files/12311561/screencapture-127-0-0-1-5500-index-html-2023-08-10-17_06_43.pdf)

### Checklist
- [x] App run correctly
- [x] The code has been tested in the local environment.
- [x] No convention errors

2023-08-11 06:57 UTC, st-ngabui requested changes

2023-08-11 06:57 UTC, st-ngabui commented on stylesheet/scss/base/_all.scss
> +@import "variable";
thiếu endline, e check mấy file khác nữa

2023-08-11 06:57 UTC, st-ngabui commented on stylesheet/scss/base/_base.scss
> +}
tạo file _badge.scss trong module rồi bỏ những mục này vào

2023-08-11 06:57 UTC, st-ngabui commented on stylesheet/scss/base/_base.scss
> +}
Những mục này tại sao lại để trong base? _base.scss chỉ chứa để CSS những thứ chung nhất cho các thẻ như thẻ body, còn style module hay layout thì em để vào thư mục tương ứng nha

2023-08-11 06:57 UTC, st-ngabui commented on stylesheet/scss/base/_reset.scss
> +}
file reset cần reset thêm nhiều style của các thẻ khác như a, ul, li, button

2023-08-11 06:57 UTC, st-ngabui commented on stylesheet/scss/base/_variable.scss
> +  )
Nếu đã gom nhóm variable trong $color rồi thì những var phía trên bỏ đi em

2023-08-11 06:57 UTC, st-ngabui commented on stylesheet/scss/layout/_grid.scss
> +}
Em thêm mục .container vào trong grid này nữa

2023-08-11 06:57 UTC, st-ngabui commented on stylesheet/scss/layout/_header.scss
> +}
Sao header mà e chỉ CSS ít như này. Em style tất cả những phần liên quan đến header bỏ vaò đây nha

2023-08-11 06:57 UTC, st-ngabui commented on stylesheet/scss/module/_icon.scss
> +}
Sao cái này lại bỏ trong _icon.scss em?

2023-08-11 06:57 UTC, st-ngabui commented on stylesheet/scss/page/_home-page.scss
> +.home-header {
phần CSS của header thì e tạo file `_header.scss` trong thư mục layout rồi e bỏ CSS vào

2023-08-13 02:28 UTC, st-ngabui requested changes
Em xem lại cách đặt các style CSS vào các file cho hợp lý, và đặt tên class có thể tái sử dụng được

2023-08-13 02:28 UTC, st-ngabui commented on stylesheet/scss/page/_home-page.scss
> +      }
Em xem lại selector chỗ này

2023-08-13 02:28 UTC, st-ngabui commented on stylesheet/scss/page/_home-page.scss
> +        .shopping-content-name {
Sử dụng selector .&-name cho ngắn gọn e nha, check lại những chỗ khác nữa

2023-08-13 02:28 UTC, st-ngabui commented on stylesheet/scss/page/_home-page.scss
> +}
Bỏ phần style của footer vào file _footer.scss của thư mục layout

2023-08-13 02:28 UTC, st-ngabui commented on stylesheet/scss/page/_home-page.scss
> +  }
Tại sao list product của 2 section` .section-product` và `.section-today-product` style trên figma giống nhau mà e lại đặt tên class khác nhau và CSS riêng cho 2 phần như này

2023-08-15 01:21 UTC, cmvn-truongle commented on stylesheet/scss/page/_home-page.scss
> +  }
dạ phần này em lỡ đặt riêng mấy bài sau em để chung hết rùi ạ

2023-08-15 07:45 UTC, merged